import './globals.css'
import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import Header from '../app/components/Header'
// const inter = Inter({ subsets: ['latin'] })
import { Poppins } from 'next/font/google'

const poppins = Poppins({
  weight: '300',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Movie-app-Full stack project',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en"  >
      
      <body 
     className={poppins.className}  suppressHydrationWarning={true}>

        <Header/>
        {children}

        </body>
    </html>
  )
}
